---
database:
  host: 192.168.1.1
  user: xxxx
  pass: xxxx
  port: 3306
  name: xxx
  charset: utf8mb4

eptank:
  dir: xxxx

pixiv:
  id: xxxx
  pw: xxxx
  user: 
  maxpost: 
  maxpostartist: 
  select:
    xxxx: yyyyy #comment

patreon:
  id: xxxx
  pw: yyyy



